In [2]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("Student.csv")

In [6]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [10]:
df.shape

(10, 5)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     object
 2   class   10 non-null     object
 3   marks   10 non-null     float64
 4   age     10 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes

In [12]:
df.dtype

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [13]:
df.head()

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [14]:
df.head(7)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19

In [15]:
df.tail()

   roll    name class  marks  age
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [16]:
df.tail(3)

   roll   name class  marks  age
7     8  amita    BE  68.33   23
8     9   amol    TE  56.75   20
9    10  anmol    BE  78.66   21

In [17]:
df.values

array([[1, 'anil', 'TE', 56.77, 22],
       [2, 'amit', 'TE', 59.77, 21],
       [3, 'aniket', 'BE', 76.88, 19],
       [4, 'ajinkya', 'TE', 69.66, 20],
       [5, 'asha', 'TE', 63.28, 20],
       [6, 'ayesha', 'BE', 49.55, 20],
       [7, 'amar', 'BE', 65.34, 19],
       [8, 'amita', 'BE', 68.33, 23],
       [9, 'amol', 'TE', 56.75, 20],
       [10, 'anmol', 'BE', 78.66, 21]], dtype=object)

In [18]:
df.T

,0,1,2,3,4,5,6,7,8,9
roll,1,2,3,4,5,6,7,8,9,10
name,anil,amit,aniket,ajinkya,asha,ayesha,amar,amita,amol,anmol
class,TE,TE,BE,TE,TE,BE,BE,BE,TE,BE
marks,56.77,59.77,76.88,69.66,63.28,49.55,65.34,68.33,56.75,78.66
age,22,21,19,20,20,20,19,23,20,21

In [19]:
# slicing

In [20]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [21]:
df.iloc[1:4,1:4]

      name class  marks
1     amit    TE  59.77
2   aniket    BE  76.88
3  ajinkya    TE  69.66

In [30]:
df.iloc[1:5,[0,1,3]]

   roll     name  marks
1     2     amit  59.77
2     3   aniket  76.88
3     4  ajinkya  69.66
4     5     asha  63.28

In [31]:
#  methods on columns/series

In [34]:
df['name'].str.upper()

0       ANIL
1       AMIT
2     ANIKET
3    AJINKYA
4       ASHA
5     AYESHA
6       AMAR
7      AMITA
8       AMOL
9      ANMOL
Name: name, dtype: object

In [36]:
df['name'].str.lower()

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [37]:
df['name'].str.startswith('a')

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: name, dtype: bool

In [38]:
df['name'].str.startswith('r')

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: name, dtype: bool

In [40]:
df['name'].str.count('amar')

0    0
1    0
2    0
3    0
4    0
5    0
6    1
7    0
8    0
9    0
Name: name, dtype: int64

In [41]:
# add or modify columns

In [42]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [48]:
gender=['m','m','m','m','f','f','m','f','m','m']

In [49]:
df['gender']=gender

In [50]:
df

   roll     name class  marks  age gender
0     1     anil    TE  56.77   22      m
1     2     amit    TE  59.77   21      m
2     3   aniket    BE  76.88   19      m
3     4  ajinkya    TE  69.66   20      m
4     5     asha    TE  63.28   20      f
5     6   ayesha    BE  49.55   20      f
6     7     amar    BE  65.34   19      m
7     8    amita    BE  68.33   23      f
8     9     amol    TE  56.75   20      m
9    10    anmol    BE  78.66   21      m

In [53]:
df['roll']=df['roll']+100

In [54]:
df

   roll     name class  marks  age gender
0   101     anil    TE  56.77   22      m
1   102     amit    TE  59.77   21      m
2   103   aniket    BE  76.88   19      m
3   104  ajinkya    TE  69.66   20      m
4   105     asha    TE  63.28   20      f
5   106   ayesha    BE  49.55   20      f
6   107     amar    BE  65.34   19      m
7   108    amita    BE  68.33   23      f
8   109     amol    TE  56.75   20      m
9   110    anmol    BE  78.66   21      m

In [71]:
df['cgpa']=df['marks']/10+1.5

In [72]:
df['cgpa'] = cgpa

In [73]:
df

,roll,name,class,marks,age,gender,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,CGPA,cgpa
0,101,anil,TE,56.77,22,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.177
1,102,amit,TE,59.77,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.48,7.477
2,103,aniket,BE,76.88,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.19,9.188
3,104,ajinkya,TE,69.66,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.47,8.466
4,105,asha,TE,63.28,20,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.83,7.828
5,106,ayesha,BE,49.55,20,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,6.46,6.455
6,107,amar,BE,65.34,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.03,8.034
7,108,amita,BE,68.33,23,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.33,8.333
8,109,amol,TE,56.75,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.175
9,110,anmol,BE,78.66,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.37,9.366

In [75]:
df.sort_values(by=['class', 'marks'])

,roll,name,class,marks,age,gender,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,CGPA,cgpa
5,106,ayesha,BE,49.55,20,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,6.46,6.455
6,107,amar,BE,65.34,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.03,8.034
7,108,amita,BE,68.33,23,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.33,8.333
2,103,aniket,BE,76.88,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.19,9.188
9,110,anmol,BE,78.66,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.37,9.366
8,109,amol,TE,56.75,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.175
0,101,anil,TE,56.77,22,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.177
1,102,amit,TE,59.77,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.48,7.477
4,105,asha,TE,63.28,20,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.83,7.828
3,104,ajinkya,TE,69.66,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.47,8.466

In [77]:
df['marks'].max()

78.66

In [78]:
df['marks'].min()

49.55

In [79]:
df['marks'].mean()

np.float64(64.499)

In [81]:
df.describe()

,roll,marks,age,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,CGPA,cgpa
count,10.00000,10.000000,10.000000,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,10.000,1.000000e+01,10.000,1.000000e+01,10.000,10.000000,10.000000
mean,105.50000,64.499000,20.500000,7.177000e+00,7.477000e+00,9.188000e+00,8.466000e+00,7.828000e+00,6.455,8.034000e+00,8.333,7.175000e+00,9.366,7.952000,7.949900
std,3.02765,9.207179,1.269296,9.362223e-16,1.872445e-15,1.872445e-15,1.872445e-15,9.362223e-16,0.000,1.872445e-15,0.000,9.362223e-16,0.000,0.919925,0.920718
min,101.00000,49.550000,19.000000,7.177000e+00,7.477000e+00,9.188000e+00,8.466000e+00,7.828000e+00,6.455,8.034000e+00,8.333,7.175000e+00,9.366,6.460000,6.455000
25%,103.25000,57.520000,20.000000,7.177000e+00,7.477000e+00,9.188000e+00,8.466000e+00,7.828000e+00,6.455,8.034000e+00,8.333,7.175000e+00,9.366,7.255000,7.252000
50%,105.50000,64.310000,20.000000,7.177000e+00,7.477000e+00,9.188000e+00,8.466000e+00,7.828000e+00,6.455,8.034000e+00,8.333,7.175000e+00,9.366,7.930000,7.931000
75%,107.75000,69.327500,21.000000,7.177000e+00,7.477000e+00,9.188000e+00,8.466000e+00,7.828000e+00,6.455,8.034000e+00,8.333,7.175000e+00,9.366,8.435000,8.432750
max,110.00000,78.660000,23.000000,7.177000e+00,7.477000e+00,9.188000e+00,8.466000e+00,7.828000e+00,6.455,8.034000e+00,8.333,7.175000e+00,9.366,9.370000,9.366000

In [82]:
# groupby

In [84]:
gr=df.groupby("class")

In [85]:
gr.groups

{'BE': [2, 5, 6, 7, 9], 'TE': [0, 1, 3, 4, 8]}

In [87]:
gr.get_group('BE')

,roll,name,class,marks,age,gender,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,CGPA,cgpa
2,103,aniket,BE,76.88,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.19,9.188
5,106,ayesha,BE,49.55,20,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,6.46,6.455
6,107,amar,BE,65.34,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.03,8.034
7,108,amita,BE,68.33,23,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.33,8.333
9,110,anmol,BE,78.66,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.37,9.366

In [88]:
gr.min()

,roll,name,marks,age,gender,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,CGPA,cgpa
class,,,,,,,,,,,,,,,,,
BE,103,amar,49.55,19,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,6.46,6.455
TE,101,ajinkya,56.75,20,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.175

In [89]:
gr['marks'].mean()

class
BE    67.752
TE    61.246
Name: marks, dtype: float64

In [90]:
df['marks']>60

0    False
1    False
2     True
3     True
4     True
5    False
6     True
7     True
8    False
9     True
Name: marks, dtype: bool

In [92]:
df[df['marks']>60]

,roll,name,class,marks,age,gender,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,CGPA,cgpa
2,103,aniket,BE,76.88,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.19,9.188
3,104,ajinkya,TE,69.66,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.47,8.466
4,105,asha,TE,63.28,20,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.83,7.828
6,107,amar,BE,65.34,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.03,8.034
7,108,amita,BE,68.33,23,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.33,8.333
9,110,anmol,BE,78.66,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.37,9.366

In [96]:
df[(df['class'] == 'BE') & (df['marks'] > 60)]

,roll,name,class,marks,age,gender,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,CGPA,cgpa
2,103,aniket,BE,76.88,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.19,9.188
6,107,amar,BE,65.34,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.03,8.034
7,108,amita,BE,68.33,23,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.33,8.333
9,110,anmol,BE,78.66,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.37,9.366

In [98]:
# drop

In [97]:
df

,roll,name,class,marks,age,gender,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,CGPA,cgpa
0,101,anil,TE,56.77,22,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.177
1,102,amit,TE,59.77,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.48,7.477
2,103,aniket,BE,76.88,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.19,9.188
3,104,ajinkya,TE,69.66,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.47,8.466
4,105,asha,TE,63.28,20,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.83,7.828
5,106,ayesha,BE,49.55,20,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,6.46,6.455
6,107,amar,BE,65.34,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.03,8.034
7,108,amita,BE,68.33,23,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.33,8.333
8,109,amol,TE,56.75,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.175
9,110,anmol,BE,78.66,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.37,9.366

In [99]:
df.drop(4)

,roll,name,class,marks,age,gender,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,CGPA,cgpa
0,101,anil,TE,56.77,22,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.177
1,102,amit,TE,59.77,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.48,7.477
2,103,aniket,BE,76.88,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.19,9.188
3,104,ajinkya,TE,69.66,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.47,8.466
5,106,ayesha,BE,49.55,20,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,6.46,6.455
6,107,amar,BE,65.34,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.03,8.034
7,108,amita,BE,68.33,23,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.33,8.333
8,109,amol,TE,56.75,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.175
9,110,anmol,BE,78.66,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.37,9.366

In [100]:
df.drop([4,5,6])

,roll,name,class,marks,age,gender,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,CGPA,cgpa
0,101,anil,TE,56.77,22,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.177
1,102,amit,TE,59.77,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.48,7.477
2,103,aniket,BE,76.88,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.19,9.188
3,104,ajinkya,TE,69.66,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.47,8.466
7,108,amita,BE,68.33,23,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.33,8.333
8,109,amol,TE,56.75,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.175
9,110,anmol,BE,78.66,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.37,9.366

In [101]:
# drop name column

In [110]:
df.drop(columns=['name','class'])

,roll,marks,age,gender,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,CGPA,cgpa
0,101,56.77,22,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.177
1,102,59.77,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.48,7.477
2,103,76.88,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.19,9.188
3,104,69.66,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.47,8.466
4,105,63.28,20,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.83,7.828
5,106,49.55,20,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,6.46,6.455
6,107,65.34,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.03,8.034
7,108,68.33,23,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.33,8.333
8,109,56.75,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.175
9,110,78.66,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.37,9.366

In [106]:
df.drop('name',axis=1)

,roll,class,marks,age,gender,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,CGPA,cgpa
0,101,TE,56.77,22,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.177
1,102,TE,59.77,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.48,7.477
2,103,BE,76.88,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.19,9.188
3,104,TE,69.66,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.47,8.466
4,105,TE,63.28,20,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.83,7.828
5,106,BE,49.55,20,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,6.46,6.455
6,107,BE,65.34,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.03,8.034
7,108,BE,68.33,23,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.33,8.333
8,109,TE,56.75,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.175
9,110,BE,78.66,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.37,9.366

In [107]:
# drop column name and class

In [108]:
df.drop(['name','class'],axis=1)

,roll,marks,age,gender,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,CGPA,cgpa
0,101,56.77,22,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.177
1,102,59.77,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.48,7.477
2,103,76.88,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.19,9.188
3,104,69.66,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.47,8.466
4,105,63.28,20,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.83,7.828
5,106,49.55,20,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,6.46,6.455
6,107,65.34,19,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.03,8.034
7,108,68.33,23,f,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,8.33,8.333
8,109,56.75,20,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,7.18,7.175
9,110,78.66,21,m,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,9.37,9.366

In [117]:
df.drop(['CGPA'],axis=1,inplace=True)

In [118]:
df

,roll,name,class,marks,age,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366
0,101,anil,TE,56.77,22,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366
1,102,amit,TE,59.77,21,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366
2,103,aniket,BE,76.88,19,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366
3,104,ajinkya,TE,69.66,20,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366
4,105,asha,TE,63.28,20,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366
5,106,ayesha,BE,49.55,20,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366
6,107,amar,BE,65.34,19,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366
7,108,amita,BE,68.33,23,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366
8,109,amol,TE,56.75,20,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366
9,110,anmol,BE,78.66,21,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366

In [121]:
import pandas as pd

df2 = pd.DataFrame({
    'roll': df['roll'],
    'gender': gender, 
    'cgpa': df['marks']/10+1.5
})

In [122]:
df2

   roll gender   cgpa
0   101      m  7.177
1   102      m  7.477
2   103      m  9.188
3   104      m  8.466
4   105      f  7.828
5   106      f  6.455
6   107      m  8.034
7   108      f  8.333
8   109      m  7.175
9   110      m  9.366

In [123]:
pd.merge(df,df2)

,roll,name,class,marks,age,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,gender,cgpa
0,101,anil,TE,56.77,22,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,m,7.177
1,102,amit,TE,59.77,21,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,m,7.477
2,103,aniket,BE,76.88,19,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,m,9.188
3,104,ajinkya,TE,69.66,20,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,m,8.466
4,105,asha,TE,63.28,20,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,f,7.828
5,106,ayesha,BE,49.55,20,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,f,6.455
6,107,amar,BE,65.34,19,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,m,8.034
7,108,amita,BE,68.33,23,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,f,8.333
8,109,amol,TE,56.75,20,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,m,7.175
9,110,anmol,BE,78.66,21,7.177,7.477,9.188,8.466,7.828,6.455,8.034,8.333,7.175,9.366,m,9.366