In [6]:
import pandas as pd
import numpy as np

In [7]:
roll=pd.Series([1,2,3,4,5])
name=pd.Series(['Sia','Ravi','Geet','Ajinkya','Avinash'])
marks=pd.Series([87,59,40,67,90])

In [8]:
df=pd.DataFrame(
    {
        'id':roll,
        'name':name,
        'marks':marks
    }
)

In [9]:
df

   id     name  marks
0   1      Sia     87
1   2     Ravi     59
2   3     Geet     40
3   4  Ajinkya     67
4   5  Avinash     90

In [10]:
df.ndim

2

In [11]:
df.shape

(5, 3)

In [12]:
df.size

15

In [13]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [ ]:
"""
url --> https://mitu.co.in/dataset --> will connenct to drive folder
"""

In [14]:
pwd

'C:\\Users\\Chandrakant'

In [16]:
df=pd.read_csv("Student.csv")

In [17]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [18]:
df=pd.read_csv("Student1.csv")

In [19]:
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [20]:
df=pd.read_csv("Student3.csv")

In [21]:
df

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
4      5     asha    TE   63.28   NaN
5      6   ayesha    BE     NaN  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
9      9     amol    TE   56.75  20.0
10    10    anmol    BE   78.66   NaN
11    11   surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
14    14   sachin   NaN   59.33  21.0
15    15  shalini    TE   63.45  20.0